CREATE TABLE USERS(
  id INT PRIMARY KEY AUTO_INCREMENT,
  INSS VARCHAR(20) UNIQUE NOT NULL,
  LASTNAME VARCHAR(40) NOT NULL,
  FIRSTNAME VARCHAR(40),
  STREET VARCHAR(60),
  HOUSENUMBER VARCHAR(10),
  POSTALCODE VARCHAR(10),
  CITY VARCHAR(20) NOT NULL);