CREATE TABLE ROLES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ROLE VARCHAR(50)
    );

CREATE TABLE USER_ROLES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT,
    ROLE_ID INT,
    CONSTRAINT FK_UserId FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_RoleId FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
);
